CREATE TABLE `order_payments` (
  `id` int(11) NOT NULL,
  `order_id` int(11) DEFAULT NULL COMMENT 'FK ke orders (nullable karena order dibuat setelah payment success)',
  `cart_id` int(11) NOT NULL COMMENT 'FK ke cart',
  `user_id` int(11) NOT NULL COMMENT 'FK ke users',
  `xendit_invoice_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ID invoice dari Xendit',
  `xendit_external_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'External ID yang kita kirim ke Xendit',
  `payment_method` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(15,2) NOT NULL COMMENT 'Total amount',
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT 'IDR',
  `status` enum('pending','paid','expired','failed','cancelled') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `invoice_url` text COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'URL invoice Xendit',
  `payment_details` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Detail pembayaran (VA number, QR string, etc)',
  `expiry_date` datetime DEFAULT NULL COMMENT 'Waktu expired invoice',
  `paid_at` datetime DEFAULT NULL COMMENT 'Waktu pembayaran berhasil',
  `xendit_callback_payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Raw payload dari Xendit webhook',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `fee_type` enum('percent','flat') COLLATE utf8mb4_unicode_ci DEFAULT 'percent',
  `platform_fee_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `merchant_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `fee_percent` decimal(5,2) DEFAULT NULL,
  `fee_flat` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;